{{- $redisPass := include "sentry.redis.password" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sentry.fullname" . }}-snuba
  labels:
    app: sentry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  settings.py: |
    import os

    from snuba.settings import *

    env = os.environ.get

    DEBUG = env("DEBUG", "0").lower() in ("1", "true")

    DEFAULT_RETENTION_DAYS = env("SENTRY_EVENT_RETENTION_DAYS", 90)

    # Clickhouse Options
    CLUSTERS = [
      {
        "host": env("CLICKHOUSE_HOST", {{ include "sentry.clickhouse.host" . | quote }}),
        "port": int({{ include "sentry.clickhouse.port" . }}),
        "user":  env("CLICKHOUSE_USER", "default"),
        "password": env("CLICKHOUSE_PASSWORD", ""),
        "database": env("CLICKHOUSE_DATABASE", "default"),
        "http_port": {{ include "sentry.clickhouse.http_port" . }},
        "storage_sets": {
            "cdc",
            "discover",
            "events",
            "events_ro",
            "metrics",
            "migrations",
            "outcomes",
            "querylog",
            "sessions",
            "transactions",
            "transactions_ro",
            "transactions_v2",
            "errors_v2",
            "errors_v2_ro",
            "profiles",
            "replays",
            "generic_metrics_sets",
            "generic_metrics_distributions",
        },
        {{- if or (and .Values.clickhouse.enabled (not .Values.clickhouse.singleNode)) (not .Values.externalClickhouse.singleNode) }}
        "single_node": False,
        {{- end }}
        {{- if or .Values.clickhouse.enabled (not .Values.externalClickhouse.singleNode) }}
        "cluster_name": {{ include "sentry.clickhouse.cluster.name" . | quote }},
        "distributed_cluster_name": {{ include "sentry.clickhouse.cluster.name" . | quote }},
        {{- else }}
        "single_node": True,
        {{- end }}
      },
    ]

    {{ if and (not .Values.kafka.enabled) .Values.externalKafka.topics }}
    {{- with .Values.externalKafka.topics }}
    KAFKA_TOPIC_MAP = {
      "events": {{ .sentryEvents | quote }},
      "event-replacements": {{ .replacement | quote }},
      "snuba-commit-log": {{ .commitLog | quote }},
      "cdc": {{ .cdc | default "cdc" | quote }},
      "snuba-metrics": {{ .snubaMetrics | default "snuba-metrics" | quote }},
      "outcomes": {{ .outcomes | quote }},
      "ingest-sessions": {{ .ingestSessions | quote }},
      "snuba-sessions-commit-log": {{ .commitLog | quote }},
      "snuba-metrics-commit-log": {{ .commitLog | quote }},
      "scheduled-subscriptions-events": {{ .scheduledSubscriptionsEvents | default "scheduled-subscriptions-events" | quote }},
      "scheduled-subscriptions-transactions": {{ .scheduledSubscriptionsTransactions | default "scheduled-subscriptions-transactions" | quote }},
      "scheduled-subscriptions-sessions": {{ .scheduledSubscriptionsSessions | default "scheduled-subscriptions-sessions" | quote }},
      "scheduled-subscriptions-metrics": {{ .scheduledSubscriptionsMetrics | default "scheduled-subscriptions-metrics" | quote }},
      "events-subscription-results": {{ .eventsSubscriptionResults | quote }},
      "transactions-subscription-results": {{ .transactionsSubscriptionResults | quote }},
      "sessions-subscription-results": {{ .sessionsSubscriptionResults | default "sessions-subscription-results" | quote }},
      "metrics-subscription-results": {{ .metricsSubscriptionResults | default "metrics-subscription-results" | quote }},
      "snuba-queries": {{ .snubaQueries | default "snuba-queries" | quote }},
      "processed-profiles": {{ .processedProfiles | default "processed-profiles" | quote }},
      "snuba-dead-letter-inserts": {{ .snubaDeadLetterInserts | default "snuba-dead-letter-inserts" | quote }},
    }
    {{- end }}
    {{- end }}


    # Redis Options
    REDIS_HOST = {{ include "sentry.redis.host" . | quote }}
    REDIS_PORT = {{ include "sentry.redis.port" . }}
    {{- if $redisPass }}
    REDIS_PASSWORD = {{ $redisPass | quote }}
    {{- end }}
    REDIS_DB = int(env("REDIS_DB", 1))

{{- if .Values.metrics.enabled }}
    DOGSTATSD_HOST = "{{ template "sentry.fullname" . }}-metrics"
    DOGSTATSD_PORT = 9125
{{- end }}

    SENTRY_DSN = env("SENTRY_DSN")

{{ .Values.config.snubaSettingsPy | indent 4 }}
