apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-subscription-consumer-transactions
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "16"
  {{- end }}
spec:
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: subscription-consumer-transactions
  replicas: {{ .Values.snuba.subscriptionConsumerTransactions.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.subscriptionConsumerTransactions.annotations }}
{{ toYaml .Values.snuba.subscriptionConsumerTransactions.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: subscription-consumer-transactions
        {{- if .Values.snuba.subscriptionConsumerTransactions.podLabels }}
{{ toYaml .Values.snuba.subscriptionConsumerTransactions.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.subscriptionConsumerTransactions.affinity }}
{{ toYaml .Values.snuba.subscriptionConsumerTransactions.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerTransactions.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.subscriptionConsumerTransactions.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.subscriptionConsumerTransactions.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.subscriptionConsumerTransactions.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        args:
          - subscriptions
          - --auto-offset-reset=latest
          - --delay-seconds=60
          - --schedule-ttl=60
          - --dataset=transactions
          {{- if and (not .Values.kafka.enabled) .Values.externalKafka.topics }}
          {{- with .Values.externalKafka.topics }}
          - --topic={{ .sentryEvents }}
          - --result-topic={{ .transactionsSubscriptionResults }}
          - --commit-log-topic={{ .commitLog }}
          {{- end }}
          {{- else }}
          - --topic=events
          - --result-topic=transactions-subscription-results
          - --commit-log-topic=snuba-commit-log
          - --commit-log-group=snuba-transactions-consumers
          - --consumer-group=snuba-transactions-subscriptions-consumers
          {{- end }}
          {{- if and (not .Values.kafka.enabled) .Values.externalKafka.consumerGroups }}
          {{- with .Values.externalKafka.consumerGroups }}
          - --consumer-group={{ .snubaTransactionsSubscriptionsConsumers }}
          - --commit-log-group={{ .transactionCommitLog }}
          {{- end }}
          {{- end }}
          {{- if .Values.snuba.subscriptionConsumerTransactions.maxQueryWorkers }}
          - --max-query-workers={{ .Values.snuba.subscriptionConsumerTransactions.maxQueryWorkers }}
          {{- end }}
          - --log-level
          - {{ .Values.snuba.logging.level }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.subscriptionConsumerTransactions.env }}
{{ toYaml .Values.snuba.subscriptionConsumerTransactions.env | indent 8 }}
{{- end }}
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
        resources:
{{ toYaml .Values.snuba.subscriptionConsumerTransactions.resources | indent 10 }}
      volumes:
        - name: config
          configMap:
            name: {{ template "sentry.fullname" . }}-snuba
