apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sentry.fullname" . }}-snuba-outcomes-consumer
  labels:
    app: {{ template "sentry.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    app.kubernetes.io/managed-by: "Helm"
  {{- if .Values.asHook }}
  {{- /* Add the Helm annotations so that deployment after asHook from true to false works */}}
  annotations:
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "17"
  {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-outcomes-consumer
  replicas: {{ .Values.snuba.outcomesConsumer.replicas }}
  template:
    metadata:
      annotations:
        checksum/snubaSettingsPy: {{ .Values.config.snubaSettingsPy | sha256sum }}
        checksum/config.yaml: {{ include (print $.Template.BasePath "/configmap-snuba.yaml") . | sha256sum }}
        {{- if .Values.snuba.outcomesConsumer.annotations }}
{{ toYaml .Values.snuba.outcomesConsumer.annotations | indent 8 }}
        {{- end }}
      labels:
        app: {{ template "sentry.fullname" . }}
        release: "{{ .Release.Name }}"
        role: snuba-outcomes-consumer
        {{- if .Values.snuba.outcomesConsumer.podLabels }}
{{ toYaml .Values.snuba.outcomesConsumer.podLabels | indent 8 }}
        {{- end }}
    spec:
      affinity:
      {{- if .Values.snuba.outcomesConsumer.affinity }}
{{ toYaml .Values.snuba.outcomesConsumer.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.outcomesConsumer.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.snuba.outcomesConsumer.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.outcomesConsumer.tolerations }}
      tolerations:
{{ toYaml .Values.snuba.outcomesConsumer.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.images.snuba.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.images.snuba.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
{{ toYaml .Values.dnsConfig | indent 8 }}
      {{- end }}
      {{- if .Values.snuba.outcomesConsumer.securityContext }}
      securityContext:
{{ toYaml .Values.snuba.outcomesConsumer.securityContext | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}-snuba
        image: "{{ template "snuba.image" . }}"
        imagePullPolicy: {{ default "IfNotPresent" .Values.images.snuba.pullPolicy }}
        args:
        - consumer
        - --storage
        - outcomes_raw
        - "--auto-offset-reset"
        - "{{ .Values.snuba.outcomesConsumer.autoOffsetReset }}"
        - --max-batch-size 
        - "{{ default "3" .Values.snuba.outcomesConsumer.maxBatchSize }}"
        {{- if .Values.snuba.outcomesConsumer.maxBatchTimeMs }}
        - "--max-batch-time-ms"
        - "{{ .Values.snuba.outcomesConsumer.maxBatchTimeMs }}"
        {{- end }}
        {{- if .Values.snuba.outcomesConsumer.queuedMaxMessagesKbytes }}
        - "--queued-max-messages-kbytes"
        - "{{ .Values.snuba.outcomesConsumer.queuedMaxMessagesKbytes }}"
        {{- end }}
        {{- if .Values.snuba.outcomesConsumer.queuedMinMessages }}
        - "--queued-min-messages"
        - "{{ .Values.snuba.outcomesConsumer.queuedMinMessages }}"
        {{- end }}
        {{- if and (not .Values.kafka.enabled) .Values.externalKafka.topics }}
        {{- with .Values.externalKafka.topics }}
        - --raw-events-topic
        - {{ .outcomes | quote }}
        - --replacements-topic
        - {{ .replacement | quote }}
        - --commit-log-topic
        - {{ .commitLog | quote }}
        {{- end }}
        - --consumer-group
        - {{ .Values.externalKafka.consumerGroups.commitLog | quote }}
        {{- end }}
        - --log-level
        - {{ .Values.snuba.logging.level }}
        {{- if .Values.snuba.outcomesConsumer.processes }}
        - --processes
        - {{ .Values.snuba.outcomesConsumer.processes | quote }}
        - --input-block-size
        - {{ required "A valid .Values.outcomesConsumer.inputBlockSize is required" .Values.snuba.outcomesConsumer.inputBlockSize | quote }}
        - --output-block-size
        - {{ required "A valid .Values.outcomesConsumer.outputBlockSize is required" .Values.snuba.outcomesConsumer.outputBlockSize | quote }}
        {{- end }}
        ports:
        - containerPort: {{ template "snuba.port" }}
        env:
{{ include "sentry.snuba.env" . | indent 8 }}
{{- if .Values.snuba.outcomesConsumer.env }}
{{ toYaml .Values.snuba.outcomesConsumer.env | indent 8 }}
{{- end }}
        envFrom:
        - secretRef:
            name: {{ template "sentry.fullname" . }}-snuba-env
        volumeMounts:
        - mountPath: /etc/snuba
          name: config
          readOnly: true
        {{- if .Values.snuba.outcomesConsumer.processes }}
        - mountPath: /dev/shm
          name: shm
        {{- end }}
{{- if .Values.snuba.outcomesConsumer.volumeMounts }}
{{ toYaml .Values.snuba.outcomesConsumer.volumeMounts | indent 8 }}
{{- end }}
        resources:
{{ toYaml .Values.snuba.outcomesConsumer.resources | indent 10 }}
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name }}-snuba
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "sentry.fullname" . }}-snuba
        {{- if .Values.snuba.outcomesConsumer.processes }}
        - emptyDir:
            medium: Memory
          name: shm
        {{- end }}
{{- if .Values.snuba.outcomesConsumer.volumes }}
{{ toYaml .Values.snuba.outcomesConsumer.volumes | indent 8 }}
{{- end }}
